# Для стадии сборки
FROM node:18-alpine AS builder

WORKDIR /app
COPY backend/package*.json ./
RUN npm ci
COPY backend/ .
RUN npm run build

# Для стадии продакшена
FROM node:18-alpine

WORKDIR /app
RUN apk add --no-cache dumb-init

COPY backend/package*.json ./
RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

EXPOSE 3001
ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "dist/index.js"]
